dependencies:
  - pandas=0.24.2
  - xlrd=1.2.0
  - numpy=1.16.4
  - pathlib
  - bokeh=1.2.0
  - requests
  - pip
  - pip:
    - nbserverproxy
    - jupyter-server-proxy
    - jupyter-dash
    - grid2viz
